package todo.todo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Date;
import java.util.List;

@Controller
@RequestMapping(path = "/")
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TodoRepository todoRepository;


    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewTodo (@RequestParam String content
            ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Todo existing = todoRepository.findByContent(content);

        if(existing == null){
            Todo n = new Todo();
            n.setContent(content);
            n.setCreation(new Date());

            todoRepository.save(n);
            return "Saved";
        }

        return "Already existing todo";

    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Todo> getAllUsers() {
        // This returns a JSON or XML with the users
        return todoRepository.findAll();
    }
}
